// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0

package sqlc

import (
	"database/sql"
	"time"
)

type Follow struct {
	FollowingUserID int32     `json:"following_user_id"`
	FollowedUserID  int32     `json:"followed_user_id"`
	CreatedAt       time.Time `json:"created_at"`
}

type Post struct {
	ID    int32  `json:"id"`
	Title string `json:"title"`
	// Content of the post
	Body      sql.NullString `json:"body"`
	UserID    int32          `json:"user_id"`
	Status    string         `json:"status"`
	CreatedAt time.Time      `json:"created_at"`
}

type User struct {
	ID        int32     `json:"id"`
	Username  string    `json:"username"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
}
